[package]
name = "feld-cli"
version = "0.1.0"
edition = "2021"
description = "cli for the arcane"
license = "MIT"
authors = ["felden"]
repository = "https://github.com/feldenserra/feld-cli"

[dependencies]
colored = "3.0.0"

[[bin]]
name = "feld"
path = "src/main.rs"
