[package]
name = "feld-cli"
version = "0.0.1"
edition = "2021"
description = "cli for the arcane"
license = "GNU General Public License v3.0"
author = "felden"
repository = "https://github.com/feldenserra/feld-cli"

[dependencies]
