[package]
name = "feld-cli"
version = "0.0.1"
edition = "2021"
description = "cli for the arcane"
license = "MIT"
authors = ["felden"]
repository = "https://github.com/feldenserra/feld-cli"

[dependencies]
